version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
