name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v3'

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        token: '${{ github.token }}'
        chart: 'charts/argo-cd'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'